# .travis.yml -- Travis CI configuration for the MPS
# $Id$
# See <http://about.travis-ci.org/docs/user/languages/c/>.
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
install:
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get -qq update
  - test "$TRAVIS_OS_NAME" = "linux" && sudo apt-get install -y automake1.11 autoconf2.64
matrix:
  exclude:
    - os: osx
      compiler: gcc
notifications:
  email:
    - mps-travis@ravenbrook.com
  irc: "irc.freenode.net#memorypoolsystem"
script:
  - autoreconf -vif && ./configure --prefix=$PWD/prefix && make install && make test
