# .travis.yml -- Travis CI configuration for the MPS
# $Id$
# See <http://about.travis-ci.org/docs/user/languages/c/>.
language: c
os:
  - linux
    - install:
      - sudo apt-get install automake autoconf
  - osx
    - install:
      - brew install automake autoconf
compiler:
  - clang
  - gcc
matrix:
  exclude:
    - os: osx
      compiler: gcc
notifications:
  email:
    - mps-travis@ravenbrook.com
  irc: "irc.freenode.net#memorypoolsystem"
script:
  - ./configure --prefix=$PWD/prefix && make install && make test
